FastCgiRequest: Start implementing `conduit::RequestExt`
Was getting this error about the lifetimes in the trait impl:

    error[E0308]: method not compatible with trait
       --> src/lib.rs:137:4
        |
    137 |    fn host(&'a self) -> conduit::Host<'a> {
        |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
        |
        = note: expected fn pointer `fn(&'a FastCgiRequest<'static>) -> conduit::Host<'a>`
                   found fn pointer `fn(&'a FastCgiRequest<'static>) -> conduit::Host<'a>`
    note: the lifetime `'a` as defined on the method body at 137:4...
       --> src/lib.rs:137:4
        |
    137 |    fn host(&'a self) -> conduit::Host<'a> {
        |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    note: ...does not necessarily outlive the lifetime `'a` as defined on the impl at 124:6
       --> src/lib.rs:124:6
        |
    124 | impl<'a> conduit::RequestExt for FastCgiRequest {
        |      ^^

    error[E0308]: method not compatible with trait
       --> src/lib.rs:137:4
        |
    137 |    fn host(&'a self) -> conduit::Host<'a> {
        |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
        |
        = note: expected fn pointer `fn(&'a FastCgiRequest<'static>) -> conduit::Host<'a>`
                   found fn pointer `fn(&'a FastCgiRequest<'static>) -> conduit::Host<'a>`
    note: the lifetime `'a` as defined on the impl at 124:6...
       --> src/lib.rs:124:6
        |
    124 | impl<'a> conduit::RequestExt for FastCgiRequest {
        |      ^^
    note: ...does not necessarily outlive the lifetime `'a` as defined on the method body at 137:4
       --> src/lib.rs:137:4
        |
    137 |    fn host(&'a self) -> conduit::Host<'a> {
        |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Learned from these resources that the problem arose because the `impl`
uses an `'a` lifetime, but the lifetime on the `host()` method need to
be a different one:

https://github.com/rust-lang/rust/issues/56423
https://stackoverflow.com/questions/24847331/rust-lifetime-error-expected-concrete-lifetime-but-found-bound-lifetime/24848424#24848424